GET http://localhost:8000/products/ HTTP/1.1

###

PUT http://localhost:8000/products/2 HTTP/1.1
Content-Type: application/json

{
    "name":"Television",
    "price": 300.00,
    "stock": 5,
    "description": "An amazing product"
}

###

DELETE  http://localhost:8000/products/2 HTTP/1.1
Content-Type: application/json

{
    "name":"Television",
    "price": 300.00,
    "stock": 5,
    "description": "An amazing product"
}

###

POST http://localhost:8000/products/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM5OTAwOTk4LCJpYXQiOjE3Mzk5MDA2OTgsImp0aSI6ImMwNTgzZWUxN2I1YzRlYWFhMjc3YzQyMTI3Y2QyMzllIiwidXNlcl9pZCI6Mn0.UsaQGmuqcpd0KDcaEl3Yxb69SwdS05NqGHiIsxq5dWw

{
    "name":"Television",
    "price": 300.00,
    "stock": 5,
    "description": "An amazing product"
}

###

POST http://localhost:8000/api/token/ HTTP/1.1
Content-Type: application/json

{
    "username": "ram",
    "password": "test"
}

###

POST http://localhost:8000/api/token/refresh/ HTTP/1.1
Content-Type: application/json

{
    "refresh": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTczOTk4NzcyOCwiaWF0IjoxNzM5OTAxMzI4LCJqdGkiOiJjODA3OWIwYTc4YTM0MzkwYTdhMzMyMzNhMDI2YzNmMCIsInVzZXJfaWQiOjJ9.a0AXy-YQ15cWyyKmLUEQZekQISQwyHBfjR8cS53ekeg"
}